// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DataContracts.proto

#include <initp/http/DataContracts.pb.h>

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_DataContracts_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_DataContracts_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_LogRecordsBatchItemDto;
}  // namespace protobuf_DataContracts_2eproto
namespace UniversalLogger {
namespace ProtobufDto {
class ApiResultDtoDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ApiResultDto>
      _instance;
} _ApiResultDto_default_instance_;
class LogRecordsBatchItemDtoDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<LogRecordsBatchItemDto>
      _instance;
} _LogRecordsBatchItemDto_default_instance_;
class LogRecordsBatchDtoDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<LogRecordsBatchDto>
      _instance;
} _LogRecordsBatchDto_default_instance_;
}  // namespace ProtobufDto
}  // namespace UniversalLogger
namespace protobuf_DataContracts_2eproto {
static void InitDefaultsApiResultDto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::UniversalLogger::ProtobufDto::_ApiResultDto_default_instance_;
    new (ptr) ::UniversalLogger::ProtobufDto::ApiResultDto();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::UniversalLogger::ProtobufDto::ApiResultDto::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_ApiResultDto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsApiResultDto}, {}};

static void InitDefaultsLogRecordsBatchItemDto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::UniversalLogger::ProtobufDto::_LogRecordsBatchItemDto_default_instance_;
    new (ptr) ::UniversalLogger::ProtobufDto::LogRecordsBatchItemDto();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::UniversalLogger::ProtobufDto::LogRecordsBatchItemDto::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_LogRecordsBatchItemDto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsLogRecordsBatchItemDto}, {}};

static void InitDefaultsLogRecordsBatchDto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::UniversalLogger::ProtobufDto::_LogRecordsBatchDto_default_instance_;
    new (ptr) ::UniversalLogger::ProtobufDto::LogRecordsBatchDto();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::UniversalLogger::ProtobufDto::LogRecordsBatchDto::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_LogRecordsBatchDto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsLogRecordsBatchDto}, {
      &protobuf_DataContracts_2eproto::scc_info_LogRecordsBatchItemDto.base,}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_ApiResultDto.base);
  ::google::protobuf::internal::InitSCC(&scc_info_LogRecordsBatchItemDto.base);
  ::google::protobuf::internal::InitSCC(&scc_info_LogRecordsBatchDto.base);
}

::google::protobuf::Metadata file_level_metadata[3];
const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors[2];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::UniversalLogger::ProtobufDto::ApiResultDto, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::UniversalLogger::ProtobufDto::ApiResultDto, apiresultstatus_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::UniversalLogger::ProtobufDto::LogRecordsBatchItemDto, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::UniversalLogger::ProtobufDto::LogRecordsBatchItemDto, sequenceid_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::UniversalLogger::ProtobufDto::LogRecordsBatchItemDto, globaltimestamp_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::UniversalLogger::ProtobufDto::LogRecordsBatchItemDto, localtimestamp_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::UniversalLogger::ProtobufDto::LogRecordsBatchItemDto, internalname_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::UniversalLogger::ProtobufDto::LogRecordsBatchItemDto, level_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::UniversalLogger::ProtobufDto::LogRecordsBatchItemDto, message_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::UniversalLogger::ProtobufDto::LogRecordsBatchDto, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::UniversalLogger::ProtobufDto::LogRecordsBatchDto, hostname_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::UniversalLogger::ProtobufDto::LogRecordsBatchDto, appname_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::UniversalLogger::ProtobufDto::LogRecordsBatchDto, startupglobaltimestamp_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::UniversalLogger::ProtobufDto::LogRecordsBatchDto, startuplocaltimestamp_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::UniversalLogger::ProtobufDto::LogRecordsBatchDto, items_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::UniversalLogger::ProtobufDto::ApiResultDto)},
  { 6, -1, sizeof(::UniversalLogger::ProtobufDto::LogRecordsBatchItemDto)},
  { 17, -1, sizeof(::UniversalLogger::ProtobufDto::LogRecordsBatchDto)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::UniversalLogger::ProtobufDto::_ApiResultDto_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::UniversalLogger::ProtobufDto::_LogRecordsBatchItemDto_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::UniversalLogger::ProtobufDto::_LogRecordsBatchDto_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "DataContracts.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, file_level_enum_descriptors, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 3);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\023DataContracts.proto\022\033UniversalLogger.P"
      "rotobufDto\"X\n\014ApiResultDto\022H\n\017ApiResultS"
      "tatus\030\001 \001(\0162/.UniversalLogger.ProtobufDt"
      "o.ApiResultStatusDto\"\275\001\n\026LogRecordsBatch"
      "ItemDto\022\022\n\nSequenceId\030\001 \001(\005\022\027\n\017GlobalTim"
      "eStamp\030\002 \001(\003\022\026\n\016LocalTimeStamp\030\003 \001(\003\022\024\n\014"
      "InternalName\030\004 \001(\t\0227\n\005Level\030\005 \001(\0162(.Univ"
      "ersalLogger.ProtobufDto.LogLevelDto\022\017\n\007M"
      "essage\030\006 \001(\t\"\272\001\n\022LogRecordsBatchDto\022\020\n\010H"
      "ostName\030\001 \001(\t\022\017\n\007AppName\030\002 \001(\t\022\036\n\026StartU"
      "pGlobalTimeStamp\030\003 \001(\003\022\035\n\025StartUpLocalTi"
      "meStamp\030\004 \001(\003\022B\n\005Items\030\005 \003(\01323.Universal"
      "Logger.ProtobufDto.LogRecordsBatchItemDt"
      "o*3\n\022ApiResultStatusDto\022\020\n\014UnknownError\020"
      "\000\022\013\n\007Success\020\001*M\n\013LogLevelDto\022\t\n\005Trace\020\000"
      "\022\t\n\005Debug\020\001\022\010\n\004Info\020\002\022\010\n\004Warn\020\003\022\t\n\005Error"
      "\020\004\022\t\n\005Fatal\020\005b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 661);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "DataContracts.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_DataContracts_2eproto
namespace UniversalLogger {
namespace ProtobufDto {
const ::google::protobuf::EnumDescriptor* ApiResultStatusDto_descriptor() {
  protobuf_DataContracts_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_DataContracts_2eproto::file_level_enum_descriptors[0];
}
bool ApiResultStatusDto_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* LogLevelDto_descriptor() {
  protobuf_DataContracts_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_DataContracts_2eproto::file_level_enum_descriptors[1];
}
bool LogLevelDto_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
      return true;
    default:
      return false;
  }
}


// ===================================================================

void ApiResultDto::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ApiResultDto::kApiResultStatusFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ApiResultDto::ApiResultDto()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_DataContracts_2eproto::scc_info_ApiResultDto.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:UniversalLogger.ProtobufDto.ApiResultDto)
}
ApiResultDto::ApiResultDto(const ApiResultDto& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  apiresultstatus_ = from.apiresultstatus_;
  // @@protoc_insertion_point(copy_constructor:UniversalLogger.ProtobufDto.ApiResultDto)
}

void ApiResultDto::SharedCtor() {
  apiresultstatus_ = 0;
}

ApiResultDto::~ApiResultDto() {
  // @@protoc_insertion_point(destructor:UniversalLogger.ProtobufDto.ApiResultDto)
  SharedDtor();
}

void ApiResultDto::SharedDtor() {
}

void ApiResultDto::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* ApiResultDto::descriptor() {
  ::protobuf_DataContracts_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_DataContracts_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ApiResultDto& ApiResultDto::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_DataContracts_2eproto::scc_info_ApiResultDto.base);
  return *internal_default_instance();
}


void ApiResultDto::Clear() {
// @@protoc_insertion_point(message_clear_start:UniversalLogger.ProtobufDto.ApiResultDto)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  apiresultstatus_ = 0;
  _internal_metadata_.Clear();
}

bool ApiResultDto::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:UniversalLogger.ProtobufDto.ApiResultDto)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .UniversalLogger.ProtobufDto.ApiResultStatusDto ApiResultStatus = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_apiresultstatus(static_cast< ::UniversalLogger::ProtobufDto::ApiResultStatusDto >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:UniversalLogger.ProtobufDto.ApiResultDto)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:UniversalLogger.ProtobufDto.ApiResultDto)
  return false;
#undef DO_
}

void ApiResultDto::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:UniversalLogger.ProtobufDto.ApiResultDto)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .UniversalLogger.ProtobufDto.ApiResultStatusDto ApiResultStatus = 1;
  if (this->apiresultstatus() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->apiresultstatus(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:UniversalLogger.ProtobufDto.ApiResultDto)
}

::google::protobuf::uint8* ApiResultDto::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:UniversalLogger.ProtobufDto.ApiResultDto)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .UniversalLogger.ProtobufDto.ApiResultStatusDto ApiResultStatus = 1;
  if (this->apiresultstatus() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->apiresultstatus(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:UniversalLogger.ProtobufDto.ApiResultDto)
  return target;
}

size_t ApiResultDto::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:UniversalLogger.ProtobufDto.ApiResultDto)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // .UniversalLogger.ProtobufDto.ApiResultStatusDto ApiResultStatus = 1;
  if (this->apiresultstatus() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->apiresultstatus());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ApiResultDto::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:UniversalLogger.ProtobufDto.ApiResultDto)
  GOOGLE_DCHECK_NE(&from, this);
  const ApiResultDto* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ApiResultDto>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:UniversalLogger.ProtobufDto.ApiResultDto)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:UniversalLogger.ProtobufDto.ApiResultDto)
    MergeFrom(*source);
  }
}

void ApiResultDto::MergeFrom(const ApiResultDto& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:UniversalLogger.ProtobufDto.ApiResultDto)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.apiresultstatus() != 0) {
    set_apiresultstatus(from.apiresultstatus());
  }
}

void ApiResultDto::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:UniversalLogger.ProtobufDto.ApiResultDto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ApiResultDto::CopyFrom(const ApiResultDto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:UniversalLogger.ProtobufDto.ApiResultDto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ApiResultDto::IsInitialized() const {
  return true;
}

void ApiResultDto::Swap(ApiResultDto* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ApiResultDto::InternalSwap(ApiResultDto* other) {
  using std::swap;
  swap(apiresultstatus_, other->apiresultstatus_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata ApiResultDto::GetMetadata() const {
  protobuf_DataContracts_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_DataContracts_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void LogRecordsBatchItemDto::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int LogRecordsBatchItemDto::kSequenceIdFieldNumber;
const int LogRecordsBatchItemDto::kGlobalTimeStampFieldNumber;
const int LogRecordsBatchItemDto::kLocalTimeStampFieldNumber;
const int LogRecordsBatchItemDto::kInternalNameFieldNumber;
const int LogRecordsBatchItemDto::kLevelFieldNumber;
const int LogRecordsBatchItemDto::kMessageFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

LogRecordsBatchItemDto::LogRecordsBatchItemDto()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_DataContracts_2eproto::scc_info_LogRecordsBatchItemDto.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:UniversalLogger.ProtobufDto.LogRecordsBatchItemDto)
}
LogRecordsBatchItemDto::LogRecordsBatchItemDto(const LogRecordsBatchItemDto& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  internalname_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.internalname().size() > 0) {
    internalname_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.internalname_);
  }
  message_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.message().size() > 0) {
    message_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.message_);
  }
  ::memcpy(&globaltimestamp_, &from.globaltimestamp_,
    static_cast<size_t>(reinterpret_cast<char*>(&level_) -
    reinterpret_cast<char*>(&globaltimestamp_)) + sizeof(level_));
  // @@protoc_insertion_point(copy_constructor:UniversalLogger.ProtobufDto.LogRecordsBatchItemDto)
}

void LogRecordsBatchItemDto::SharedCtor() {
  internalname_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  message_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&globaltimestamp_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&level_) -
      reinterpret_cast<char*>(&globaltimestamp_)) + sizeof(level_));
}

LogRecordsBatchItemDto::~LogRecordsBatchItemDto() {
  // @@protoc_insertion_point(destructor:UniversalLogger.ProtobufDto.LogRecordsBatchItemDto)
  SharedDtor();
}

void LogRecordsBatchItemDto::SharedDtor() {
  internalname_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  message_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void LogRecordsBatchItemDto::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* LogRecordsBatchItemDto::descriptor() {
  ::protobuf_DataContracts_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_DataContracts_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const LogRecordsBatchItemDto& LogRecordsBatchItemDto::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_DataContracts_2eproto::scc_info_LogRecordsBatchItemDto.base);
  return *internal_default_instance();
}


void LogRecordsBatchItemDto::Clear() {
// @@protoc_insertion_point(message_clear_start:UniversalLogger.ProtobufDto.LogRecordsBatchItemDto)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  internalname_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  message_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&globaltimestamp_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&level_) -
      reinterpret_cast<char*>(&globaltimestamp_)) + sizeof(level_));
  _internal_metadata_.Clear();
}

bool LogRecordsBatchItemDto::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:UniversalLogger.ProtobufDto.LogRecordsBatchItemDto)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 SequenceId = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &sequenceid_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int64 GlobalTimeStamp = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &globaltimestamp_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int64 LocalTimeStamp = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &localtimestamp_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string InternalName = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_internalname()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->internalname().data(), static_cast<int>(this->internalname().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "UniversalLogger.ProtobufDto.LogRecordsBatchItemDto.InternalName"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .UniversalLogger.ProtobufDto.LogLevelDto Level = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(40u /* 40 & 0xFF */)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_level(static_cast< ::UniversalLogger::ProtobufDto::LogLevelDto >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string Message = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(50u /* 50 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_message()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->message().data(), static_cast<int>(this->message().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "UniversalLogger.ProtobufDto.LogRecordsBatchItemDto.Message"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:UniversalLogger.ProtobufDto.LogRecordsBatchItemDto)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:UniversalLogger.ProtobufDto.LogRecordsBatchItemDto)
  return false;
#undef DO_
}

void LogRecordsBatchItemDto::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:UniversalLogger.ProtobufDto.LogRecordsBatchItemDto)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 SequenceId = 1;
  if (this->sequenceid() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->sequenceid(), output);
  }

  // int64 GlobalTimeStamp = 2;
  if (this->globaltimestamp() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(2, this->globaltimestamp(), output);
  }

  // int64 LocalTimeStamp = 3;
  if (this->localtimestamp() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(3, this->localtimestamp(), output);
  }

  // string InternalName = 4;
  if (this->internalname().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->internalname().data(), static_cast<int>(this->internalname().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "UniversalLogger.ProtobufDto.LogRecordsBatchItemDto.InternalName");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      4, this->internalname(), output);
  }

  // .UniversalLogger.ProtobufDto.LogLevelDto Level = 5;
  if (this->level() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      5, this->level(), output);
  }

  // string Message = 6;
  if (this->message().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->message().data(), static_cast<int>(this->message().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "UniversalLogger.ProtobufDto.LogRecordsBatchItemDto.Message");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      6, this->message(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:UniversalLogger.ProtobufDto.LogRecordsBatchItemDto)
}

::google::protobuf::uint8* LogRecordsBatchItemDto::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:UniversalLogger.ProtobufDto.LogRecordsBatchItemDto)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 SequenceId = 1;
  if (this->sequenceid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->sequenceid(), target);
  }

  // int64 GlobalTimeStamp = 2;
  if (this->globaltimestamp() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(2, this->globaltimestamp(), target);
  }

  // int64 LocalTimeStamp = 3;
  if (this->localtimestamp() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(3, this->localtimestamp(), target);
  }

  // string InternalName = 4;
  if (this->internalname().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->internalname().data(), static_cast<int>(this->internalname().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "UniversalLogger.ProtobufDto.LogRecordsBatchItemDto.InternalName");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->internalname(), target);
  }

  // .UniversalLogger.ProtobufDto.LogLevelDto Level = 5;
  if (this->level() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      5, this->level(), target);
  }

  // string Message = 6;
  if (this->message().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->message().data(), static_cast<int>(this->message().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "UniversalLogger.ProtobufDto.LogRecordsBatchItemDto.Message");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        6, this->message(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:UniversalLogger.ProtobufDto.LogRecordsBatchItemDto)
  return target;
}

size_t LogRecordsBatchItemDto::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:UniversalLogger.ProtobufDto.LogRecordsBatchItemDto)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string InternalName = 4;
  if (this->internalname().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->internalname());
  }

  // string Message = 6;
  if (this->message().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->message());
  }

  // int64 GlobalTimeStamp = 2;
  if (this->globaltimestamp() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->globaltimestamp());
  }

  // int64 LocalTimeStamp = 3;
  if (this->localtimestamp() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->localtimestamp());
  }

  // int32 SequenceId = 1;
  if (this->sequenceid() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->sequenceid());
  }

  // .UniversalLogger.ProtobufDto.LogLevelDto Level = 5;
  if (this->level() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->level());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void LogRecordsBatchItemDto::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:UniversalLogger.ProtobufDto.LogRecordsBatchItemDto)
  GOOGLE_DCHECK_NE(&from, this);
  const LogRecordsBatchItemDto* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const LogRecordsBatchItemDto>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:UniversalLogger.ProtobufDto.LogRecordsBatchItemDto)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:UniversalLogger.ProtobufDto.LogRecordsBatchItemDto)
    MergeFrom(*source);
  }
}

void LogRecordsBatchItemDto::MergeFrom(const LogRecordsBatchItemDto& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:UniversalLogger.ProtobufDto.LogRecordsBatchItemDto)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.internalname().size() > 0) {

    internalname_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.internalname_);
  }
  if (from.message().size() > 0) {

    message_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.message_);
  }
  if (from.globaltimestamp() != 0) {
    set_globaltimestamp(from.globaltimestamp());
  }
  if (from.localtimestamp() != 0) {
    set_localtimestamp(from.localtimestamp());
  }
  if (from.sequenceid() != 0) {
    set_sequenceid(from.sequenceid());
  }
  if (from.level() != 0) {
    set_level(from.level());
  }
}

void LogRecordsBatchItemDto::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:UniversalLogger.ProtobufDto.LogRecordsBatchItemDto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void LogRecordsBatchItemDto::CopyFrom(const LogRecordsBatchItemDto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:UniversalLogger.ProtobufDto.LogRecordsBatchItemDto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool LogRecordsBatchItemDto::IsInitialized() const {
  return true;
}

void LogRecordsBatchItemDto::Swap(LogRecordsBatchItemDto* other) {
  if (other == this) return;
  InternalSwap(other);
}
void LogRecordsBatchItemDto::InternalSwap(LogRecordsBatchItemDto* other) {
  using std::swap;
  internalname_.Swap(&other->internalname_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  message_.Swap(&other->message_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(globaltimestamp_, other->globaltimestamp_);
  swap(localtimestamp_, other->localtimestamp_);
  swap(sequenceid_, other->sequenceid_);
  swap(level_, other->level_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata LogRecordsBatchItemDto::GetMetadata() const {
  protobuf_DataContracts_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_DataContracts_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void LogRecordsBatchDto::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int LogRecordsBatchDto::kHostNameFieldNumber;
const int LogRecordsBatchDto::kAppNameFieldNumber;
const int LogRecordsBatchDto::kStartUpGlobalTimeStampFieldNumber;
const int LogRecordsBatchDto::kStartUpLocalTimeStampFieldNumber;
const int LogRecordsBatchDto::kItemsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

LogRecordsBatchDto::LogRecordsBatchDto()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_DataContracts_2eproto::scc_info_LogRecordsBatchDto.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:UniversalLogger.ProtobufDto.LogRecordsBatchDto)
}
LogRecordsBatchDto::LogRecordsBatchDto(const LogRecordsBatchDto& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      items_(from.items_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  hostname_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.hostname().size() > 0) {
    hostname_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.hostname_);
  }
  appname_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.appname().size() > 0) {
    appname_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.appname_);
  }
  ::memcpy(&startupglobaltimestamp_, &from.startupglobaltimestamp_,
    static_cast<size_t>(reinterpret_cast<char*>(&startuplocaltimestamp_) -
    reinterpret_cast<char*>(&startupglobaltimestamp_)) + sizeof(startuplocaltimestamp_));
  // @@protoc_insertion_point(copy_constructor:UniversalLogger.ProtobufDto.LogRecordsBatchDto)
}

void LogRecordsBatchDto::SharedCtor() {
  hostname_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  appname_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&startupglobaltimestamp_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&startuplocaltimestamp_) -
      reinterpret_cast<char*>(&startupglobaltimestamp_)) + sizeof(startuplocaltimestamp_));
}

LogRecordsBatchDto::~LogRecordsBatchDto() {
  // @@protoc_insertion_point(destructor:UniversalLogger.ProtobufDto.LogRecordsBatchDto)
  SharedDtor();
}

void LogRecordsBatchDto::SharedDtor() {
  hostname_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  appname_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void LogRecordsBatchDto::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* LogRecordsBatchDto::descriptor() {
  ::protobuf_DataContracts_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_DataContracts_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const LogRecordsBatchDto& LogRecordsBatchDto::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_DataContracts_2eproto::scc_info_LogRecordsBatchDto.base);
  return *internal_default_instance();
}


void LogRecordsBatchDto::Clear() {
// @@protoc_insertion_point(message_clear_start:UniversalLogger.ProtobufDto.LogRecordsBatchDto)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  items_.Clear();
  hostname_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  appname_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&startupglobaltimestamp_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&startuplocaltimestamp_) -
      reinterpret_cast<char*>(&startupglobaltimestamp_)) + sizeof(startuplocaltimestamp_));
  _internal_metadata_.Clear();
}

bool LogRecordsBatchDto::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:UniversalLogger.ProtobufDto.LogRecordsBatchDto)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string HostName = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_hostname()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->hostname().data(), static_cast<int>(this->hostname().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "UniversalLogger.ProtobufDto.LogRecordsBatchDto.HostName"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string AppName = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_appname()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->appname().data(), static_cast<int>(this->appname().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "UniversalLogger.ProtobufDto.LogRecordsBatchDto.AppName"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int64 StartUpGlobalTimeStamp = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &startupglobaltimestamp_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int64 StartUpLocalTimeStamp = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u /* 32 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &startuplocaltimestamp_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .UniversalLogger.ProtobufDto.LogRecordsBatchItemDto Items = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(42u /* 42 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_items()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:UniversalLogger.ProtobufDto.LogRecordsBatchDto)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:UniversalLogger.ProtobufDto.LogRecordsBatchDto)
  return false;
#undef DO_
}

void LogRecordsBatchDto::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:UniversalLogger.ProtobufDto.LogRecordsBatchDto)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string HostName = 1;
  if (this->hostname().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->hostname().data(), static_cast<int>(this->hostname().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "UniversalLogger.ProtobufDto.LogRecordsBatchDto.HostName");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->hostname(), output);
  }

  // string AppName = 2;
  if (this->appname().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->appname().data(), static_cast<int>(this->appname().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "UniversalLogger.ProtobufDto.LogRecordsBatchDto.AppName");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->appname(), output);
  }

  // int64 StartUpGlobalTimeStamp = 3;
  if (this->startupglobaltimestamp() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(3, this->startupglobaltimestamp(), output);
  }

  // int64 StartUpLocalTimeStamp = 4;
  if (this->startuplocaltimestamp() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(4, this->startuplocaltimestamp(), output);
  }

  // repeated .UniversalLogger.ProtobufDto.LogRecordsBatchItemDto Items = 5;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->items_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      5,
      this->items(static_cast<int>(i)),
      output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:UniversalLogger.ProtobufDto.LogRecordsBatchDto)
}

::google::protobuf::uint8* LogRecordsBatchDto::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:UniversalLogger.ProtobufDto.LogRecordsBatchDto)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string HostName = 1;
  if (this->hostname().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->hostname().data(), static_cast<int>(this->hostname().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "UniversalLogger.ProtobufDto.LogRecordsBatchDto.HostName");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->hostname(), target);
  }

  // string AppName = 2;
  if (this->appname().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->appname().data(), static_cast<int>(this->appname().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "UniversalLogger.ProtobufDto.LogRecordsBatchDto.AppName");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->appname(), target);
  }

  // int64 StartUpGlobalTimeStamp = 3;
  if (this->startupglobaltimestamp() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(3, this->startupglobaltimestamp(), target);
  }

  // int64 StartUpLocalTimeStamp = 4;
  if (this->startuplocaltimestamp() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(4, this->startuplocaltimestamp(), target);
  }

  // repeated .UniversalLogger.ProtobufDto.LogRecordsBatchItemDto Items = 5;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->items_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        5, this->items(static_cast<int>(i)), deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:UniversalLogger.ProtobufDto.LogRecordsBatchDto)
  return target;
}

size_t LogRecordsBatchDto::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:UniversalLogger.ProtobufDto.LogRecordsBatchDto)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated .UniversalLogger.ProtobufDto.LogRecordsBatchItemDto Items = 5;
  {
    unsigned int count = static_cast<unsigned int>(this->items_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->items(static_cast<int>(i)));
    }
  }

  // string HostName = 1;
  if (this->hostname().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->hostname());
  }

  // string AppName = 2;
  if (this->appname().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->appname());
  }

  // int64 StartUpGlobalTimeStamp = 3;
  if (this->startupglobaltimestamp() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->startupglobaltimestamp());
  }

  // int64 StartUpLocalTimeStamp = 4;
  if (this->startuplocaltimestamp() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->startuplocaltimestamp());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void LogRecordsBatchDto::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:UniversalLogger.ProtobufDto.LogRecordsBatchDto)
  GOOGLE_DCHECK_NE(&from, this);
  const LogRecordsBatchDto* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const LogRecordsBatchDto>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:UniversalLogger.ProtobufDto.LogRecordsBatchDto)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:UniversalLogger.ProtobufDto.LogRecordsBatchDto)
    MergeFrom(*source);
  }
}

void LogRecordsBatchDto::MergeFrom(const LogRecordsBatchDto& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:UniversalLogger.ProtobufDto.LogRecordsBatchDto)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  items_.MergeFrom(from.items_);
  if (from.hostname().size() > 0) {

    hostname_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.hostname_);
  }
  if (from.appname().size() > 0) {

    appname_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.appname_);
  }
  if (from.startupglobaltimestamp() != 0) {
    set_startupglobaltimestamp(from.startupglobaltimestamp());
  }
  if (from.startuplocaltimestamp() != 0) {
    set_startuplocaltimestamp(from.startuplocaltimestamp());
  }
}

void LogRecordsBatchDto::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:UniversalLogger.ProtobufDto.LogRecordsBatchDto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void LogRecordsBatchDto::CopyFrom(const LogRecordsBatchDto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:UniversalLogger.ProtobufDto.LogRecordsBatchDto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool LogRecordsBatchDto::IsInitialized() const {
  return true;
}

void LogRecordsBatchDto::Swap(LogRecordsBatchDto* other) {
  if (other == this) return;
  InternalSwap(other);
}
void LogRecordsBatchDto::InternalSwap(LogRecordsBatchDto* other) {
  using std::swap;
  CastToBase(&items_)->InternalSwap(CastToBase(&other->items_));
  hostname_.Swap(&other->hostname_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  appname_.Swap(&other->appname_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(startupglobaltimestamp_, other->startupglobaltimestamp_);
  swap(startuplocaltimestamp_, other->startuplocaltimestamp_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata LogRecordsBatchDto::GetMetadata() const {
  protobuf_DataContracts_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_DataContracts_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace ProtobufDto
}  // namespace UniversalLogger
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::UniversalLogger::ProtobufDto::ApiResultDto* Arena::CreateMaybeMessage< ::UniversalLogger::ProtobufDto::ApiResultDto >(Arena* arena) {
  return Arena::CreateInternal< ::UniversalLogger::ProtobufDto::ApiResultDto >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::UniversalLogger::ProtobufDto::LogRecordsBatchItemDto* Arena::CreateMaybeMessage< ::UniversalLogger::ProtobufDto::LogRecordsBatchItemDto >(Arena* arena) {
  return Arena::CreateInternal< ::UniversalLogger::ProtobufDto::LogRecordsBatchItemDto >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::UniversalLogger::ProtobufDto::LogRecordsBatchDto* Arena::CreateMaybeMessage< ::UniversalLogger::ProtobufDto::LogRecordsBatchDto >(Arena* arena) {
  return Arena::CreateInternal< ::UniversalLogger::ProtobufDto::LogRecordsBatchDto >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
