// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DataContracts.proto

#ifndef PROTOBUF_INCLUDED_DataContracts_2eproto
#define PROTOBUF_INCLUDED_DataContracts_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_DataContracts_2eproto 

namespace protobuf_DataContracts_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[3];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_DataContracts_2eproto
namespace UniversalLogger {
namespace ProtobufDto {
class ApiResultDto;
class ApiResultDtoDefaultTypeInternal;
extern ApiResultDtoDefaultTypeInternal _ApiResultDto_default_instance_;
class LogRecordsBatchDto;
class LogRecordsBatchDtoDefaultTypeInternal;
extern LogRecordsBatchDtoDefaultTypeInternal _LogRecordsBatchDto_default_instance_;
class LogRecordsBatchItemDto;
class LogRecordsBatchItemDtoDefaultTypeInternal;
extern LogRecordsBatchItemDtoDefaultTypeInternal _LogRecordsBatchItemDto_default_instance_;
}  // namespace ProtobufDto
}  // namespace UniversalLogger
namespace google {
namespace protobuf {
template<> ::UniversalLogger::ProtobufDto::ApiResultDto* Arena::CreateMaybeMessage<::UniversalLogger::ProtobufDto::ApiResultDto>(Arena*);
template<> ::UniversalLogger::ProtobufDto::LogRecordsBatchDto* Arena::CreateMaybeMessage<::UniversalLogger::ProtobufDto::LogRecordsBatchDto>(Arena*);
template<> ::UniversalLogger::ProtobufDto::LogRecordsBatchItemDto* Arena::CreateMaybeMessage<::UniversalLogger::ProtobufDto::LogRecordsBatchItemDto>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace UniversalLogger {
namespace ProtobufDto {

enum ApiResultStatusDto {
  UnknownError = 0,
  Success = 1,
  ApiResultStatusDto_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  ApiResultStatusDto_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool ApiResultStatusDto_IsValid(int value);
const ApiResultStatusDto ApiResultStatusDto_MIN = UnknownError;
const ApiResultStatusDto ApiResultStatusDto_MAX = Success;
const int ApiResultStatusDto_ARRAYSIZE = ApiResultStatusDto_MAX + 1;

const ::google::protobuf::EnumDescriptor* ApiResultStatusDto_descriptor();
inline const ::std::string& ApiResultStatusDto_Name(ApiResultStatusDto value) {
  return ::google::protobuf::internal::NameOfEnum(
    ApiResultStatusDto_descriptor(), value);
}
inline bool ApiResultStatusDto_Parse(
    const ::std::string& name, ApiResultStatusDto* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ApiResultStatusDto>(
    ApiResultStatusDto_descriptor(), name, value);
}
enum LogLevelDto {
  Trace = 0,
  Debug = 1,
  Info = 2,
  Warn = 3,
  Error = 4,
  Fatal = 5,
  LogLevelDto_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  LogLevelDto_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool LogLevelDto_IsValid(int value);
const LogLevelDto LogLevelDto_MIN = Trace;
const LogLevelDto LogLevelDto_MAX = Fatal;
const int LogLevelDto_ARRAYSIZE = LogLevelDto_MAX + 1;

const ::google::protobuf::EnumDescriptor* LogLevelDto_descriptor();
inline const ::std::string& LogLevelDto_Name(LogLevelDto value) {
  return ::google::protobuf::internal::NameOfEnum(
    LogLevelDto_descriptor(), value);
}
inline bool LogLevelDto_Parse(
    const ::std::string& name, LogLevelDto* value) {
  return ::google::protobuf::internal::ParseNamedEnum<LogLevelDto>(
    LogLevelDto_descriptor(), name, value);
}
// ===================================================================

class ApiResultDto : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:UniversalLogger.ProtobufDto.ApiResultDto) */ {
 public:
  ApiResultDto();
  virtual ~ApiResultDto();

  ApiResultDto(const ApiResultDto& from);

  inline ApiResultDto& operator=(const ApiResultDto& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ApiResultDto(ApiResultDto&& from) noexcept
    : ApiResultDto() {
    *this = ::std::move(from);
  }

  inline ApiResultDto& operator=(ApiResultDto&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ApiResultDto& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ApiResultDto* internal_default_instance() {
    return reinterpret_cast<const ApiResultDto*>(
               &_ApiResultDto_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(ApiResultDto* other);
  friend void swap(ApiResultDto& a, ApiResultDto& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ApiResultDto* New() const final {
    return CreateMaybeMessage<ApiResultDto>(NULL);
  }

  ApiResultDto* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ApiResultDto>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ApiResultDto& from);
  void MergeFrom(const ApiResultDto& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ApiResultDto* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .UniversalLogger.ProtobufDto.ApiResultStatusDto ApiResultStatus = 1;
  void clear_apiresultstatus();
  static const int kApiResultStatusFieldNumber = 1;
  ::UniversalLogger::ProtobufDto::ApiResultStatusDto apiresultstatus() const;
  void set_apiresultstatus(::UniversalLogger::ProtobufDto::ApiResultStatusDto value);

  // @@protoc_insertion_point(class_scope:UniversalLogger.ProtobufDto.ApiResultDto)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  int apiresultstatus_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_DataContracts_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class LogRecordsBatchItemDto : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:UniversalLogger.ProtobufDto.LogRecordsBatchItemDto) */ {
 public:
  LogRecordsBatchItemDto();
  virtual ~LogRecordsBatchItemDto();

  LogRecordsBatchItemDto(const LogRecordsBatchItemDto& from);

  inline LogRecordsBatchItemDto& operator=(const LogRecordsBatchItemDto& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  LogRecordsBatchItemDto(LogRecordsBatchItemDto&& from) noexcept
    : LogRecordsBatchItemDto() {
    *this = ::std::move(from);
  }

  inline LogRecordsBatchItemDto& operator=(LogRecordsBatchItemDto&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const LogRecordsBatchItemDto& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const LogRecordsBatchItemDto* internal_default_instance() {
    return reinterpret_cast<const LogRecordsBatchItemDto*>(
               &_LogRecordsBatchItemDto_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(LogRecordsBatchItemDto* other);
  friend void swap(LogRecordsBatchItemDto& a, LogRecordsBatchItemDto& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline LogRecordsBatchItemDto* New() const final {
    return CreateMaybeMessage<LogRecordsBatchItemDto>(NULL);
  }

  LogRecordsBatchItemDto* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<LogRecordsBatchItemDto>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const LogRecordsBatchItemDto& from);
  void MergeFrom(const LogRecordsBatchItemDto& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LogRecordsBatchItemDto* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string InternalName = 4;
  void clear_internalname();
  static const int kInternalNameFieldNumber = 4;
  const ::std::string& internalname() const;
  void set_internalname(const ::std::string& value);
  #if LANG_CXX11
  void set_internalname(::std::string&& value);
  #endif
  void set_internalname(const char* value);
  void set_internalname(const char* value, size_t size);
  ::std::string* mutable_internalname();
  ::std::string* release_internalname();
  void set_allocated_internalname(::std::string* internalname);

  // string Message = 6;
  void clear_message();
  static const int kMessageFieldNumber = 6;
  const ::std::string& message() const;
  void set_message(const ::std::string& value);
  #if LANG_CXX11
  void set_message(::std::string&& value);
  #endif
  void set_message(const char* value);
  void set_message(const char* value, size_t size);
  ::std::string* mutable_message();
  ::std::string* release_message();
  void set_allocated_message(::std::string* message);

  // int64 GlobalTimeStamp = 2;
  void clear_globaltimestamp();
  static const int kGlobalTimeStampFieldNumber = 2;
  ::google::protobuf::int64 globaltimestamp() const;
  void set_globaltimestamp(::google::protobuf::int64 value);

  // int64 LocalTimeStamp = 3;
  void clear_localtimestamp();
  static const int kLocalTimeStampFieldNumber = 3;
  ::google::protobuf::int64 localtimestamp() const;
  void set_localtimestamp(::google::protobuf::int64 value);

  // int32 SequenceId = 1;
  void clear_sequenceid();
  static const int kSequenceIdFieldNumber = 1;
  ::google::protobuf::int32 sequenceid() const;
  void set_sequenceid(::google::protobuf::int32 value);

  // .UniversalLogger.ProtobufDto.LogLevelDto Level = 5;
  void clear_level();
  static const int kLevelFieldNumber = 5;
  ::UniversalLogger::ProtobufDto::LogLevelDto level() const;
  void set_level(::UniversalLogger::ProtobufDto::LogLevelDto value);

  // @@protoc_insertion_point(class_scope:UniversalLogger.ProtobufDto.LogRecordsBatchItemDto)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr internalname_;
  ::google::protobuf::internal::ArenaStringPtr message_;
  ::google::protobuf::int64 globaltimestamp_;
  ::google::protobuf::int64 localtimestamp_;
  ::google::protobuf::int32 sequenceid_;
  int level_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_DataContracts_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class LogRecordsBatchDto : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:UniversalLogger.ProtobufDto.LogRecordsBatchDto) */ {
 public:
  LogRecordsBatchDto();
  virtual ~LogRecordsBatchDto();

  LogRecordsBatchDto(const LogRecordsBatchDto& from);

  inline LogRecordsBatchDto& operator=(const LogRecordsBatchDto& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  LogRecordsBatchDto(LogRecordsBatchDto&& from) noexcept
    : LogRecordsBatchDto() {
    *this = ::std::move(from);
  }

  inline LogRecordsBatchDto& operator=(LogRecordsBatchDto&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const LogRecordsBatchDto& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const LogRecordsBatchDto* internal_default_instance() {
    return reinterpret_cast<const LogRecordsBatchDto*>(
               &_LogRecordsBatchDto_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(LogRecordsBatchDto* other);
  friend void swap(LogRecordsBatchDto& a, LogRecordsBatchDto& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline LogRecordsBatchDto* New() const final {
    return CreateMaybeMessage<LogRecordsBatchDto>(NULL);
  }

  LogRecordsBatchDto* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<LogRecordsBatchDto>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const LogRecordsBatchDto& from);
  void MergeFrom(const LogRecordsBatchDto& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LogRecordsBatchDto* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .UniversalLogger.ProtobufDto.LogRecordsBatchItemDto Items = 5;
  int items_size() const;
  void clear_items();
  static const int kItemsFieldNumber = 5;
  ::UniversalLogger::ProtobufDto::LogRecordsBatchItemDto* mutable_items(int index);
  ::google::protobuf::RepeatedPtrField< ::UniversalLogger::ProtobufDto::LogRecordsBatchItemDto >*
      mutable_items();
  const ::UniversalLogger::ProtobufDto::LogRecordsBatchItemDto& items(int index) const;
  ::UniversalLogger::ProtobufDto::LogRecordsBatchItemDto* add_items();
  const ::google::protobuf::RepeatedPtrField< ::UniversalLogger::ProtobufDto::LogRecordsBatchItemDto >&
      items() const;

  // string HostName = 1;
  void clear_hostname();
  static const int kHostNameFieldNumber = 1;
  const ::std::string& hostname() const;
  void set_hostname(const ::std::string& value);
  #if LANG_CXX11
  void set_hostname(::std::string&& value);
  #endif
  void set_hostname(const char* value);
  void set_hostname(const char* value, size_t size);
  ::std::string* mutable_hostname();
  ::std::string* release_hostname();
  void set_allocated_hostname(::std::string* hostname);

  // string AppName = 2;
  void clear_appname();
  static const int kAppNameFieldNumber = 2;
  const ::std::string& appname() const;
  void set_appname(const ::std::string& value);
  #if LANG_CXX11
  void set_appname(::std::string&& value);
  #endif
  void set_appname(const char* value);
  void set_appname(const char* value, size_t size);
  ::std::string* mutable_appname();
  ::std::string* release_appname();
  void set_allocated_appname(::std::string* appname);

  // int64 StartUpGlobalTimeStamp = 3;
  void clear_startupglobaltimestamp();
  static const int kStartUpGlobalTimeStampFieldNumber = 3;
  ::google::protobuf::int64 startupglobaltimestamp() const;
  void set_startupglobaltimestamp(::google::protobuf::int64 value);

  // int64 StartUpLocalTimeStamp = 4;
  void clear_startuplocaltimestamp();
  static const int kStartUpLocalTimeStampFieldNumber = 4;
  ::google::protobuf::int64 startuplocaltimestamp() const;
  void set_startuplocaltimestamp(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:UniversalLogger.ProtobufDto.LogRecordsBatchDto)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::UniversalLogger::ProtobufDto::LogRecordsBatchItemDto > items_;
  ::google::protobuf::internal::ArenaStringPtr hostname_;
  ::google::protobuf::internal::ArenaStringPtr appname_;
  ::google::protobuf::int64 startupglobaltimestamp_;
  ::google::protobuf::int64 startuplocaltimestamp_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_DataContracts_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ApiResultDto

// .UniversalLogger.ProtobufDto.ApiResultStatusDto ApiResultStatus = 1;
inline void ApiResultDto::clear_apiresultstatus() {
  apiresultstatus_ = 0;
}
inline ::UniversalLogger::ProtobufDto::ApiResultStatusDto ApiResultDto::apiresultstatus() const {
  // @@protoc_insertion_point(field_get:UniversalLogger.ProtobufDto.ApiResultDto.ApiResultStatus)
  return static_cast< ::UniversalLogger::ProtobufDto::ApiResultStatusDto >(apiresultstatus_);
}
inline void ApiResultDto::set_apiresultstatus(::UniversalLogger::ProtobufDto::ApiResultStatusDto value) {
  
  apiresultstatus_ = value;
  // @@protoc_insertion_point(field_set:UniversalLogger.ProtobufDto.ApiResultDto.ApiResultStatus)
}

// -------------------------------------------------------------------

// LogRecordsBatchItemDto

// int32 SequenceId = 1;
inline void LogRecordsBatchItemDto::clear_sequenceid() {
  sequenceid_ = 0;
}
inline ::google::protobuf::int32 LogRecordsBatchItemDto::sequenceid() const {
  // @@protoc_insertion_point(field_get:UniversalLogger.ProtobufDto.LogRecordsBatchItemDto.SequenceId)
  return sequenceid_;
}
inline void LogRecordsBatchItemDto::set_sequenceid(::google::protobuf::int32 value) {
  
  sequenceid_ = value;
  // @@protoc_insertion_point(field_set:UniversalLogger.ProtobufDto.LogRecordsBatchItemDto.SequenceId)
}

// int64 GlobalTimeStamp = 2;
inline void LogRecordsBatchItemDto::clear_globaltimestamp() {
  globaltimestamp_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 LogRecordsBatchItemDto::globaltimestamp() const {
  // @@protoc_insertion_point(field_get:UniversalLogger.ProtobufDto.LogRecordsBatchItemDto.GlobalTimeStamp)
  return globaltimestamp_;
}
inline void LogRecordsBatchItemDto::set_globaltimestamp(::google::protobuf::int64 value) {
  
  globaltimestamp_ = value;
  // @@protoc_insertion_point(field_set:UniversalLogger.ProtobufDto.LogRecordsBatchItemDto.GlobalTimeStamp)
}

// int64 LocalTimeStamp = 3;
inline void LogRecordsBatchItemDto::clear_localtimestamp() {
  localtimestamp_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 LogRecordsBatchItemDto::localtimestamp() const {
  // @@protoc_insertion_point(field_get:UniversalLogger.ProtobufDto.LogRecordsBatchItemDto.LocalTimeStamp)
  return localtimestamp_;
}
inline void LogRecordsBatchItemDto::set_localtimestamp(::google::protobuf::int64 value) {
  
  localtimestamp_ = value;
  // @@protoc_insertion_point(field_set:UniversalLogger.ProtobufDto.LogRecordsBatchItemDto.LocalTimeStamp)
}

// string InternalName = 4;
inline void LogRecordsBatchItemDto::clear_internalname() {
  internalname_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& LogRecordsBatchItemDto::internalname() const {
  // @@protoc_insertion_point(field_get:UniversalLogger.ProtobufDto.LogRecordsBatchItemDto.InternalName)
  return internalname_.GetNoArena();
}
inline void LogRecordsBatchItemDto::set_internalname(const ::std::string& value) {
  
  internalname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:UniversalLogger.ProtobufDto.LogRecordsBatchItemDto.InternalName)
}
#if LANG_CXX11
inline void LogRecordsBatchItemDto::set_internalname(::std::string&& value) {
  
  internalname_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:UniversalLogger.ProtobufDto.LogRecordsBatchItemDto.InternalName)
}
#endif
inline void LogRecordsBatchItemDto::set_internalname(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  internalname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:UniversalLogger.ProtobufDto.LogRecordsBatchItemDto.InternalName)
}
inline void LogRecordsBatchItemDto::set_internalname(const char* value, size_t size) {
  
  internalname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:UniversalLogger.ProtobufDto.LogRecordsBatchItemDto.InternalName)
}
inline ::std::string* LogRecordsBatchItemDto::mutable_internalname() {
  
  // @@protoc_insertion_point(field_mutable:UniversalLogger.ProtobufDto.LogRecordsBatchItemDto.InternalName)
  return internalname_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* LogRecordsBatchItemDto::release_internalname() {
  // @@protoc_insertion_point(field_release:UniversalLogger.ProtobufDto.LogRecordsBatchItemDto.InternalName)
  
  return internalname_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void LogRecordsBatchItemDto::set_allocated_internalname(::std::string* internalname) {
  if (internalname != NULL) {
    
  } else {
    
  }
  internalname_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), internalname);
  // @@protoc_insertion_point(field_set_allocated:UniversalLogger.ProtobufDto.LogRecordsBatchItemDto.InternalName)
}

// .UniversalLogger.ProtobufDto.LogLevelDto Level = 5;
inline void LogRecordsBatchItemDto::clear_level() {
  level_ = 0;
}
inline ::UniversalLogger::ProtobufDto::LogLevelDto LogRecordsBatchItemDto::level() const {
  // @@protoc_insertion_point(field_get:UniversalLogger.ProtobufDto.LogRecordsBatchItemDto.Level)
  return static_cast< ::UniversalLogger::ProtobufDto::LogLevelDto >(level_);
}
inline void LogRecordsBatchItemDto::set_level(::UniversalLogger::ProtobufDto::LogLevelDto value) {
  
  level_ = value;
  // @@protoc_insertion_point(field_set:UniversalLogger.ProtobufDto.LogRecordsBatchItemDto.Level)
}

// string Message = 6;
inline void LogRecordsBatchItemDto::clear_message() {
  message_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& LogRecordsBatchItemDto::message() const {
  // @@protoc_insertion_point(field_get:UniversalLogger.ProtobufDto.LogRecordsBatchItemDto.Message)
  return message_.GetNoArena();
}
inline void LogRecordsBatchItemDto::set_message(const ::std::string& value) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:UniversalLogger.ProtobufDto.LogRecordsBatchItemDto.Message)
}
#if LANG_CXX11
inline void LogRecordsBatchItemDto::set_message(::std::string&& value) {
  
  message_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:UniversalLogger.ProtobufDto.LogRecordsBatchItemDto.Message)
}
#endif
inline void LogRecordsBatchItemDto::set_message(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:UniversalLogger.ProtobufDto.LogRecordsBatchItemDto.Message)
}
inline void LogRecordsBatchItemDto::set_message(const char* value, size_t size) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:UniversalLogger.ProtobufDto.LogRecordsBatchItemDto.Message)
}
inline ::std::string* LogRecordsBatchItemDto::mutable_message() {
  
  // @@protoc_insertion_point(field_mutable:UniversalLogger.ProtobufDto.LogRecordsBatchItemDto.Message)
  return message_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* LogRecordsBatchItemDto::release_message() {
  // @@protoc_insertion_point(field_release:UniversalLogger.ProtobufDto.LogRecordsBatchItemDto.Message)
  
  return message_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void LogRecordsBatchItemDto::set_allocated_message(::std::string* message) {
  if (message != NULL) {
    
  } else {
    
  }
  message_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), message);
  // @@protoc_insertion_point(field_set_allocated:UniversalLogger.ProtobufDto.LogRecordsBatchItemDto.Message)
}

// -------------------------------------------------------------------

// LogRecordsBatchDto

// string HostName = 1;
inline void LogRecordsBatchDto::clear_hostname() {
  hostname_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& LogRecordsBatchDto::hostname() const {
  // @@protoc_insertion_point(field_get:UniversalLogger.ProtobufDto.LogRecordsBatchDto.HostName)
  return hostname_.GetNoArena();
}
inline void LogRecordsBatchDto::set_hostname(const ::std::string& value) {
  
  hostname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:UniversalLogger.ProtobufDto.LogRecordsBatchDto.HostName)
}
#if LANG_CXX11
inline void LogRecordsBatchDto::set_hostname(::std::string&& value) {
  
  hostname_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:UniversalLogger.ProtobufDto.LogRecordsBatchDto.HostName)
}
#endif
inline void LogRecordsBatchDto::set_hostname(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  hostname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:UniversalLogger.ProtobufDto.LogRecordsBatchDto.HostName)
}
inline void LogRecordsBatchDto::set_hostname(const char* value, size_t size) {
  
  hostname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:UniversalLogger.ProtobufDto.LogRecordsBatchDto.HostName)
}
inline ::std::string* LogRecordsBatchDto::mutable_hostname() {
  
  // @@protoc_insertion_point(field_mutable:UniversalLogger.ProtobufDto.LogRecordsBatchDto.HostName)
  return hostname_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* LogRecordsBatchDto::release_hostname() {
  // @@protoc_insertion_point(field_release:UniversalLogger.ProtobufDto.LogRecordsBatchDto.HostName)
  
  return hostname_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void LogRecordsBatchDto::set_allocated_hostname(::std::string* hostname) {
  if (hostname != NULL) {
    
  } else {
    
  }
  hostname_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), hostname);
  // @@protoc_insertion_point(field_set_allocated:UniversalLogger.ProtobufDto.LogRecordsBatchDto.HostName)
}

// string AppName = 2;
inline void LogRecordsBatchDto::clear_appname() {
  appname_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& LogRecordsBatchDto::appname() const {
  // @@protoc_insertion_point(field_get:UniversalLogger.ProtobufDto.LogRecordsBatchDto.AppName)
  return appname_.GetNoArena();
}
inline void LogRecordsBatchDto::set_appname(const ::std::string& value) {
  
  appname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:UniversalLogger.ProtobufDto.LogRecordsBatchDto.AppName)
}
#if LANG_CXX11
inline void LogRecordsBatchDto::set_appname(::std::string&& value) {
  
  appname_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:UniversalLogger.ProtobufDto.LogRecordsBatchDto.AppName)
}
#endif
inline void LogRecordsBatchDto::set_appname(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  appname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:UniversalLogger.ProtobufDto.LogRecordsBatchDto.AppName)
}
inline void LogRecordsBatchDto::set_appname(const char* value, size_t size) {
  
  appname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:UniversalLogger.ProtobufDto.LogRecordsBatchDto.AppName)
}
inline ::std::string* LogRecordsBatchDto::mutable_appname() {
  
  // @@protoc_insertion_point(field_mutable:UniversalLogger.ProtobufDto.LogRecordsBatchDto.AppName)
  return appname_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* LogRecordsBatchDto::release_appname() {
  // @@protoc_insertion_point(field_release:UniversalLogger.ProtobufDto.LogRecordsBatchDto.AppName)
  
  return appname_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void LogRecordsBatchDto::set_allocated_appname(::std::string* appname) {
  if (appname != NULL) {
    
  } else {
    
  }
  appname_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), appname);
  // @@protoc_insertion_point(field_set_allocated:UniversalLogger.ProtobufDto.LogRecordsBatchDto.AppName)
}

// int64 StartUpGlobalTimeStamp = 3;
inline void LogRecordsBatchDto::clear_startupglobaltimestamp() {
  startupglobaltimestamp_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 LogRecordsBatchDto::startupglobaltimestamp() const {
  // @@protoc_insertion_point(field_get:UniversalLogger.ProtobufDto.LogRecordsBatchDto.StartUpGlobalTimeStamp)
  return startupglobaltimestamp_;
}
inline void LogRecordsBatchDto::set_startupglobaltimestamp(::google::protobuf::int64 value) {
  
  startupglobaltimestamp_ = value;
  // @@protoc_insertion_point(field_set:UniversalLogger.ProtobufDto.LogRecordsBatchDto.StartUpGlobalTimeStamp)
}

// int64 StartUpLocalTimeStamp = 4;
inline void LogRecordsBatchDto::clear_startuplocaltimestamp() {
  startuplocaltimestamp_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 LogRecordsBatchDto::startuplocaltimestamp() const {
  // @@protoc_insertion_point(field_get:UniversalLogger.ProtobufDto.LogRecordsBatchDto.StartUpLocalTimeStamp)
  return startuplocaltimestamp_;
}
inline void LogRecordsBatchDto::set_startuplocaltimestamp(::google::protobuf::int64 value) {
  
  startuplocaltimestamp_ = value;
  // @@protoc_insertion_point(field_set:UniversalLogger.ProtobufDto.LogRecordsBatchDto.StartUpLocalTimeStamp)
}

// repeated .UniversalLogger.ProtobufDto.LogRecordsBatchItemDto Items = 5;
inline int LogRecordsBatchDto::items_size() const {
  return items_.size();
}
inline void LogRecordsBatchDto::clear_items() {
  items_.Clear();
}
inline ::UniversalLogger::ProtobufDto::LogRecordsBatchItemDto* LogRecordsBatchDto::mutable_items(int index) {
  // @@protoc_insertion_point(field_mutable:UniversalLogger.ProtobufDto.LogRecordsBatchDto.Items)
  return items_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::UniversalLogger::ProtobufDto::LogRecordsBatchItemDto >*
LogRecordsBatchDto::mutable_items() {
  // @@protoc_insertion_point(field_mutable_list:UniversalLogger.ProtobufDto.LogRecordsBatchDto.Items)
  return &items_;
}
inline const ::UniversalLogger::ProtobufDto::LogRecordsBatchItemDto& LogRecordsBatchDto::items(int index) const {
  // @@protoc_insertion_point(field_get:UniversalLogger.ProtobufDto.LogRecordsBatchDto.Items)
  return items_.Get(index);
}
inline ::UniversalLogger::ProtobufDto::LogRecordsBatchItemDto* LogRecordsBatchDto::add_items() {
  // @@protoc_insertion_point(field_add:UniversalLogger.ProtobufDto.LogRecordsBatchDto.Items)
  return items_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::UniversalLogger::ProtobufDto::LogRecordsBatchItemDto >&
LogRecordsBatchDto::items() const {
  // @@protoc_insertion_point(field_list:UniversalLogger.ProtobufDto.LogRecordsBatchDto.Items)
  return items_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace ProtobufDto
}  // namespace UniversalLogger

namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::UniversalLogger::ProtobufDto::ApiResultStatusDto> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::UniversalLogger::ProtobufDto::ApiResultStatusDto>() {
  return ::UniversalLogger::ProtobufDto::ApiResultStatusDto_descriptor();
}
template <> struct is_proto_enum< ::UniversalLogger::ProtobufDto::LogLevelDto> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::UniversalLogger::ProtobufDto::LogLevelDto>() {
  return ::UniversalLogger::ProtobufDto::LogLevelDto_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_DataContracts_2eproto
